import alias from 'rollup-plugin-alias';
import resolve from 'rollup-plugin-node-resolve';
import typescript from 'rollup-plugin-typescript2';
import angular from 'rollup-plugin-angular-aot';

export default {
  input: 'tmp/esm5/main.js',
  output: {
    format: 'umd',
    file: 'dist/bundles/angular2-filemanager.umd.js',
    name: 'angular2tree',
    sourcemap: false,
    globals: {
      '@angular/animations': 'ng.angular.animations',
      '@angular/animations/browser': 'ng.angular.animations-browser',
      '@angular/core': 'ng.angular.core',
      '@angular/cdk': 'ng.angular.cdk',
      '@angular/cdk/a11y': 'ng.angular.cdk-a11y',
      '@angular/cdk/bidi': 'ng.angular.cdk-bidi',
      '@angular/cdk/coercion': 'ng.angular.cdk-coercion',
      '@angular/cdk/collections': 'ng.angular.cdk-collections',
      '@angular/cdk/keycodes': 'ng.angular.cdk-keycodes',
      '@angular/cdk/layout': 'ng.angular.cdk-layout',
      '@angular/cdk/observers': 'ng.angular.cdk-observers',
      '@angular/cdk/overlay': 'ng.angular.cdk-overlay',
      '@angular/cdk/platform': 'ng.angular.cdk-platform',
      '@angular/cdk/portal': 'ng.angular.cdk-portal',
      '@angular/cdk/rxjs': 'ng.angular.cdk-rxjs',
      '@angular/cdk/scrolling': 'ng.angular.cdk-scrolling',
      '@angular/cdk/stepper': 'ng.angular.cdk-stepper',
      '@angular/cdk/table': 'ng.angular.cdk-table',
      '@angular/common/http': 'ng.angular.common-http',
      '@angular/common': 'ng.angular.common',
      '@angular/compiler': 'ng.angular.compiler',
      '@angular/platform-browser': 'ng.angular.platform-browser',
      '@angular/platform-browser/animations': 'ng.angular.platform-browser-animations',
      '@angular/platform-browser-dynamic': 'ng.angular.platform-browser-dynamic',
      '@angular/http': 'ng.angular.http',
      '@angular/router': 'ng.angular.router',
      '@angular/forms': 'ng.angular.forms',
      'ng2-dnd': 'ng.ng2-dnd',
      'ng2-translate': 'ng.ng2-translate',
      '@ngrx/store': 'ng.ngrx.store',
      '@ngrx/store-devtools': 'ng.ngrx.store-devtools',
      '@ngrx/effects': 'ng.ngrx.effects',
      '@rign/angular2-tree': 'rign.angular2-tree',
      'angular2-uuid': 'ng.angular2-uuid',
      'angular2-notifications': 'ng.angular2-notifications',
      'angular-confirmation-popover': 'ng.angular-confirmation-popover',
      'ng2-file-upload': 'ng.ng2-file-upload',
      'ng2-img-cropper': 'ng.ng2-image-cropper',
      'rxjs/Subject': 'rxjs.Subject',
      'rxjs/Subscription': 'rxjs.Subscription',
      'rxjs/BehaviorSubject': 'rxjs.BehaviorSubject',
      'rxjs/Observable': 'rxjs.Observable',
      'rxjs/operators': 'rxjs.operators',
    }
  },
  context: 'this',
  plugins: [
    angular(),
    typescript(),
    alias({
      rxjs: __dirname + '/node_modules/rxjs-es'
    }),
    resolve({
      jsnext: true,
      main: true,
      browser: true,
      modulesOnly: true
    })
  ],
  external: [
    '@angular/animations',
    '@angular/animations/browser',
    '@angular/cdk',
    '@angular/core',
    '@angular/core/testing',
    '@angular/common',
    '@angular/common/http',
    '@angular/compiler',
    '@angular/http',
    '@angular/forms',
    '@angular/platform-browser',
    '@angular/platform-browser/animations',
    '@angular/platform-browser-dynamic',
    '@angular/router',
    '@angular/router-deprecated',
    '@ngrx/core',
    '@ngrx/store',
    '@ngrx/store/src/selector',
    '@ngrx/effects',
    '@ngrx/store-devtools',
    '@rign/angular2-tree',
    'angular-confirmation-popover',
    'angular2-uuid',
    'angular2-notifications',
    'ng2-file-upload',
    'ng2-img-cropper',
    'ng2-translate',
    'ng2-dnd',
    'ngx-contextmenu',
    'rxjs/add/operator/withLatestFrom',
    'rxjs/add/observable/combineLatest',
    'rxjs/add/observable/fromEvent',
    'rxjs/add/observable/empty',
    'rxjs/add/observable/merge',
    'rxjs/add/observable/of',
    'rxjs/add/observable/throw',
    'rxjs/observable/merge',
    'rxjs/observable/of',
    'rxjs/operators',
    'rxjs/BehaviorSubject',
    'rxjs/Subject',
    'rxjs/Observable',
    'rxjs/Subscription'
  ]
}
