export class Button {
  static ADD_FOLDER = 'ADD_FOLDER';
  static DELETE_SELECTION = 'DELETE_SELECTION';
  static INVERSE_SELECTION = 'INVERSE_SELECTION';
  static REFRESH_FILES_LIST = 'REFRESH_FILES_LIST';
  static SELECT_ALL = 'SELECT_ALL';
  static UNSELECT_ALL = 'UNSELECT_ALL';
}
